### ISSUE TITLE
问下deep-qa/src/main/resources/models/chineseFactored.ser.gz这个文件是？谢谢！

### ISSUE THREAD

**Issue by guotong1988** [ysc/QuestionAnsweringSystem#10]
console打印Loading parser from serialized file models/chineseFactored.ser.gz 
问下这个文件里面是什么内容？是怎么写的？从哪获取和怎么编辑呢？
多谢！

**Comment by ysc** [comment]
1、File chineseFactored.ser.gz is a parser model, which is trained on data from the Penn Chinese Treebank. 
Specific reference is Stanford Parser FAQ number 24: http://nlp.stanford.edu/software/parser-faq.shtml#o

2、You can train your own parser model. 
Specific reference is Stanford Parser FAQ number 5: http://nlp.stanford.edu/software/parser-faq.shtml#d
