### ISSUE TITLE
句子依存关系 和 句法树 的一些小问题？多谢！

### ISSUE THREAD

**Issue by guotong1988** [ysc/QuestionAnsweringSystem#11]
句法树: 
```
(ROOT [81.764]
  (IP [81.634]
    (NP [66.213]
      (DNP [47.088]
        (NP [46.697]
          (NP [14.063] (NR 中央电视台))
          (ADJP [5.707] (JJ 著名))
          (NP [22.350] (NN 节目) (NN 实话实说)))
        (DEG 的))
      (QP [3.267] (OD 第一任))
      (NP [9.925] (NN 主持人)))
    (VP [11.021] (VC 是)
      (NP [8.042] (PN 谁)))))
```
句子依存关系：
```
	nn(实话实说-4, 中央电视台-1)
	amod(实话实说-4, 著名-2)
	nn(实话实说-4, 节目-3)
	assmod(主持人-7, 实话实说-4)
	assm(实话实说-4, 的-5)
	nummod(主持人-7, 第一任-6)
	top(是-8, 主持人-7)
	root(ROOT-0, 是-8)
	attr(是-8, 谁-9)

```

希望大神可以给些相关资料，不懂里面字母和数字的意思，比如[]里的数字等等，多谢大神！

**Comment by ysc** [comment]
请看这个文档：
Stanford typed dependencies manual http://nlp.stanford.edu/software/dependencies_manual.pdf

**Comment by guotong1988** [comment]
这个文档好像没写句法树[]里的数字的意思？

**Comment by Michael-LiK** [comment]
ROOT：要处理文本的语句 
IP：简单从句 
NP：名词短语 
VP：动词短语 
PU：断句符，通常是句号、问号、感叹号等标点符号 
LCP：方位词短语 
PP：介词短语 
CP：由‘的’构成的表示修饰性关系的短语 
DNP：由‘的’构成的表示所属关系的短语 
ADVP：副词短语 
ADJP：形容词短语 
DP：限定词短语 
QP：量词短语 
NN：常用名词 
NR：固有名词 
NT：时间名词 
PN：代词 
VV：动词 
VC：是 
CC：表示连词 
VE：有 
VA：表语形容词 
AS：内容标记（如：了） 
VRD：动补复合词 
CD: 表示基数词 
DT: determiner 表示限定词 
EX: existential there 存在句 
FW: foreign word 外来词 
IN: preposition or conjunction, subordinating 介词或从属连词 
JJ: adjective or numeral, ordinal 形容词或序数词 
JJR: adjective, comparative 形容词比较级 
JJS: adjective, superlative 形容词最高级 
LS: list item marker 列表标识 
MD: modal auxiliary 情态助动词 
PDT: pre-determiner 前位限定词 
POS: genitive marker 所有格标记 
PRP: pronoun, personal 人称代词 
RB: adverb 副词 
RBR: adverb, comparative 副词比较级 
RBS: adverb, superlative 副词最高级 
RP: particle 小品词 
SYM: symbol 符号 
TO:”to” as preposition or infinitive marker 作为介词或不定式标记 
WDT: WH-determiner WH限定词 
WP: WH-pronoun WH代词 
WP$: WH-pronoun, possessive WH所有格代词 
WRB:Wh-adverb WH副词
