### ISSUE TITLE
questionanswer system 数据库问题

### ISSUE THREAD

**Issue by supengyu** [ysc/QuestionAnsweringSystem#13]
在tomcat环境下部署了questionanswer system,系统启动后，进入页面:http://localhost:8090/deep-qa-web-1.2/all.jsp 显示MySQL中没有缓存任何数据或MySQL未启动 ，实际数据库中有数据，是什么原因，怎么解决，谢谢

**Comment by ysc** [comment]
你应该访问页面：http://localhost:8090/deep-qa-web-1.2/index.jsp，MySQL作为数据缓存区使用，all.jsp是用于查看缓存的，因为你没有配置MYSQL数据库，所以会提示你：“MySQL中没有缓存任何数据或MySQL未启动”。

MYSQL数据库配置方法：

    在MySQL命令行中执行QuestionAnsweringSystem/deep-qa/src/main/resources/mysql/questionanswer.sql文件中的脚本   
    MySQL编码：UTF-8，
    主机：127.0.0.1
    端口：3306
    数据库：questionanswer
    用户名：root
    密码：root

**Comment by supengyu** [comment]
您好：
   非常感谢你的回信，帮我解决了问题，是由于我的mysql数据库有问题所以导致连接不上，重新安装了数据库问题就没有了，请问一下数据库中三个表，evidence,question,rewind之间的关心，假如我需要新增一个问答模式（模版），应该如何利用这三个表，再次感谢







在 2016-03-09 10:12:01，"杨尚川" <notifications@github.com> 写道：


你应该访问页面：http://localhost:8090/deep-qa-web-1.2/index.jsp，MySQL作为数据缓存区使用，all.jsp是用于查看缓存的，因为你没有配置MYSQL数据库，所以会提示你：“MySQL中没有缓存任何数据或MySQL未启动”。

MYSQL数据库配置方法：

在MySQL命令行中执行QuestionAnsweringSystem/deep-qa/src/main/resources/mysql/questionanswer.sql文件中的脚本   
MySQL编码：UTF-8，
主机：127.0.0.1
端口：3306
数据库：questionanswer
用户名：root
密码：root
