### ISSUE TITLE
关于新增一个问答模式（模板）

### ISSUE THREAD

**Issue by supengyu** [ysc/QuestionAnsweringSystem#14]
请问一下数据库中三个表，evidence,question,rewind之间的关系，假如我需要新增一个问答模式（模版），应该如何利用这三个表，再次感谢

**Comment by ysc** [comment]
数据库脚本：[https://github.com/ysc/QuestionAnsweringSystem/blob/master/deep-qa/src/main/resources/mysql/questionanswer.sql](https://github.com/ysc/QuestionAnsweringSystem/blob/master/deep-qa/src/main/resources/mysql/questionanswer.sql)

这3个表只是用来缓存（CACHE）数据，并不是必须的，数据是在线实时从网上搜的。

如果想增加新的问题类型（答案类型），则需要：
1、在枚举类org.apdplat.qa.model.QuestionType中增加新的问题类型，并在词性和问题类型之间做映射。
2、在资源目录src/main/resources/questionTypePatterns中增加新的模式匹配规则来支持新的问题类型的判定，目录中的3个文件代表不同抽象层级的模式，只需要在其中一个文件中增加新的模式即可。
3、在类org.apdplat.qa.questiontypeanalysis.QuestionTypeTransformer中将模式匹配规则映射为枚举类org.apdplat.qa.model.QuestionType的实例。
