### ISSUE TITLE
运行http://localhost:8088/deep-qa-web-1.2/index.jsp时，出现正确界面，但是提问出错

### ISSUE THREAD

**Issue by zm594406222** [ysc/QuestionAnsweringSystem#15]
type Exception report

message javax.servlet.ServletException: java.lang.OutOfMemoryError: Java heap space

description The server encountered an internal error that prevented it from fulfilling this request.

应该是jvm内存默认分配过小，便尝试修改了catalina.bat文件
set CATALINA_OPTS=-Xms512M -Xmx512M
set JAVA_OPTS=-Xms512M -Xmx512M
修改了很多次，依旧出现堆内存溢出。不知道是什么问题.

**Comment by ysc** [comment]
内存设置太小了，设大一点：-Xms3g -Xmx3g
你直接运行这个脚本：https://github.com/ysc/QuestionAnsweringSystem/blob/master/startup_tomcat.sh
