### ISSUE TITLE
BigramEvidenceScore评分规则问题

### ISSUE THREAD

**Issue by zhaopcprayer** [ysc/QuestionAnsweringSystem#16]
Tools.countsForBigram中，index > 0才计入评分，那开头一致的不算匹配成功。
比如question是姚明的女儿是谁，evidence中title是姚明的女儿叫姚沁蕾，匹配只能匹配到“的女儿”，而不会将“姚明的”计入评分，这是出于何种考虑？

**Comment by ysc** [comment]
You are totally right, this is a bug, I have fixed it. Thank you very much.
