### ISSUE TITLE
问题类型分类

### ISSUE THREAD

**Issue by endymecy** [ysc/QuestionAnsweringSystem#17]
请问一下，我部署了您的系统之后，不管我问什么问题，问题类型分类都匹配不到，最后默认为“PERSON_NAME”。这是什么原因？

**Comment by ysc** [comment]
你贴一下日志看看

**Comment by box0513** [comment]
这个问题我也碰到了。
![image](https://cloud.githubusercontent.com/assets/14118129/16943262/66a883a6-4dcd-11e6-9352-5125d74b0cfd.png)

**Comment by forgetMind** [comment]
同问，我是增加了Definition的问题，匹配不到，只是提取了网上的答案。
