### ISSUE TITLE
增加新的问题类型

### ISSUE THREAD

**Issue by Satroler** [ysc/QuestionAnsweringSystem#18]
因为在QuestionTypeTransformer把Object和Definition注释掉了，在<增加新的问题类型>中怎样增加自己想要的问题和答案类型。比如如何增加<怎样评价github网站：该网站是一个XXX的类型的网站...>这样的问答类型？

**Comment by ysc** [comment]
如何增加新的问题类型（答案类型）：

    1、在枚举类 org.apdplat.qa.model.QuestionType 中
       增加新的问题类型，并在词性和问题类型之间做映射。
       
    2、在资源目录 src/main/resources/questionTypePatterns 中增加新的模式匹配规则来支持新的问题类型的判定
       目录中的 3 个文件代表不同抽象层级的模式，只需要在其中一个文件中增加新的模式即可。
       
    3、在类 org.apdplat.qa.questiontypeanalysis.QuestionTypeTransformer 中
       将模式匹配规则映射为枚举类 org.apdplat.qa.model.QuestionType 的实例。
