### ISSUE TITLE
关于自定义问题

### ISSUE THREAD

**Issue by forgetMind** [ysc/QuestionAnsweringSystem#24]
我在QuestionAnsweringSystem/deep-qa/src/main/resources/org/apdplat/qa/files中增加了两个定义的Definition类型的问题,FilesConfig中也增加了引用，希望能够将特定的问题关联到定义好的问题答案中去，在测试的时候发现还是没有检测到实际引用，引用的是网上获取的，还请大神指点，需要怎么做才能关联到自定义的问题答案。谢谢。

**Comment by ysc** [comment]
问答系统不支持自定义答案，你可以实现自己的数据源。你需要自己看一下代码。
