### ISSUE TITLE
关于自定义问题

### ISSUE THREAD

**Issue by forgetMind** [ysc/QuestionAnsweringSystem#25]
我使用了自定义的问题答案，按照目录路径/org/apdplat/qa/files/，添加了两个文件，可是始终无法正常读取到，直接读取会抛出异常报错，请问一下是哪里配置了读取的固定文件吗，是从引用的jar中读取的吗？
我删除了引用的qa的四个库，不再报错，读取的路径也是正常的我定义的文件，可是读取的文件内容是之前拷贝的测试使用的time_material.txt中的内容（内容已经更改过），我不清楚是什么情况，是不是关联到了设定的，还请大神指点一二。

**Comment by ysc** [comment]
/org/apdplat/qa/files/ 不是问题的答案，是标注的训练语料库

**Comment by forgetMind** [comment]
多谢大神提示
