### ISSUE TITLE
项目cmd构建成功，访问出错404

### ISSUE THREAD

**Issue by dawsonjiang** [ysc/QuestionAnsweringSystem#29]
![n6 sol 82 93 pi 4 7h](https://user-images.githubusercontent.com/17867071/35203958-e9ddaaf8-ff65-11e7-863f-5b1ae8daac0c.png)

**Comment by ysc** [comment]
看看日志输出。

**Comment by Aodi** [comment]
你好，我也出现了同样的问题，请问找出问题所在了吗？ 另外请教一下如何查看日志输出。谢谢！

**Comment by xnj24** [comment]
直接在浏览器输入http://localhost:8080/   试试
