### ISSUE TITLE
希望能提供在Eclipse里部署并运行以及Debug的简单指引文档

### ISSUE THREAD

**Issue by guotong1988** [ysc/QuestionAnsweringSystem#8]
谢谢大神

**Comment by guotong1988** [comment]
mvn eclipse:eclipse
然后就能导入就能运行了，报了错
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apdplat/word/util/WordConfTools : Unsupported major.minor version 52.0
可能是java7的问题，我用java8试试

**Comment by ysc** [comment]
如何使用Eclipse在Github上开发使用Java8的Maven项目？http://my.oschina.net/apdplat/blog/403394 

对于QuestionAnsweringSystem的调试来说，你直接在Eclipse开发环境中找到有main方法的类然后打上断点跟踪调试就可以。而对于部署来说，没必要在Eclipse开发环境中部署，因为这个项目的web ui只是一个简单的壳，你在命令行运行mvn package得到war包，扔到tomcat8中部署即可。
