### ISSUE TITLE
问题类型的模式怎样获得

### ISSUE THREAD

**Issue by luffy1937** [ysc/QuestionAnsweringSystem#9]
读了这个项目的问题分类模块。
其中有level1到level3三个问题模式的文件。
我猜想的这些模式的生成方式是：
1.首先是在level1中罗列一些实际问题，并有分类。
2.level2、level3是直接根据问题类型从level1生成的。
因为我想增加几个问题类型，请指点一下怎样得到这些问题模式？@ysc

**Comment by ysc** [comment]
level1到level3是一个倒金字塔结构，从具体到抽象，准确率的概率从1开始衰减，每个级别之间没有什么关系，level1命中就会忽略level2和level3，level2命中就会忽略level3。

如果要增加问题类型，问题就比较复杂了，问题模式需要你自己去定义。
